version: '3.5'

services:
  postgres:
    container_name: uidsm_db
    image: postgres:14
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    expose:
       - 5432
    networks:
      uidsm_net:
        aliases:
          - uidsm_db
    restart: always

  uidsm_server:
      container_name: uidsm_server
      restart: always
      image: rheagroup/ui-dsm:latest
      networks:
        uidsm_net:
          aliases:
            - uidsm_server
      depends_on:
        - postgres
      ports:
        - "8080:80"
      volumes:
        - artifacts:/app/storage

  search:
    container_name: uidsm_search
    image: gitlab.esa.int:4567/rhea-generic-platform/rhea-generic-platform/gp-search-service
    environment:
      - Meilisearch__host=${MEILI_HOST:-http://uidsm_meilisearch:7700}
      - Meilisearch__key=${MEILI_MASTER_KEY:-masterkey}
      - MessageBroker__host=uidsm_rabbitmq
      - MessageBroker__port=5672
    volumes:
      - './searchlibrary:/app/Plugins'
    networks:
      - uidsm_net
    expose:
      - 80
    restart: always

  meilisearch:
    container_name: uidsm_meilisearch
    image: "getmeili/meilisearch:latest"
    environment:
      - MEILI_NO_ANALYTICS=false
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterkey}
      - MEILI_HTTP_PAYLOAD_SIZE_LIMIT=209715200
    networks:
      - uidsm_net
    expose:
      - 7700
    volumes:
      - 'meilisearch:/meili_data'
    restart: always
    
  rabbitmq:
   container_name: uidsm_rabbitmq
   image: "rabbitmq:3-management"
   restart: always
   networks:
      - uidsm_net
   expose:
      - 5672
   volumes:
      - 'rabbitmq_data:/data'

networks:
  uidsm_net:
    driver: bridge

volumes:
    postgres:
    artifacts:
    meilisearch:
    searchlibrary:
    rabbitmq_data: