name: Publish UI-DSM Docker Container

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v3
      
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
    - name: Build the Docker image and tag
      run: DOCKER_BUILDKIT=1 docker build -f Dockerfile -t rheagroup/ui-dsm:latest -t rheagroup/ui-dsm:${{ steps.vars.outputs.tag }} .
      
    - name: push $RELEASE_VERSION tag
      run: docker push rheagroup/ui-dsm:${{ steps.vars.outputs.tag }}
      
    - name: push latest tag
      run: docker push rheagroup/ui-dsm:latest